# Generated by Django 4.2.6 on 2023-11-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_camion_vans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='descripcion',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='camion',
            old_name='descripcion',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='vans',
            old_name='descripcion',
            new_name='modelo',
        ),
    ]
