# Generated by Django 4.2.6 on 2023-11-13 19:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_descripcion_auto_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
